### PR TITLE
Retreive local plugin's namespace from root pacakage's autload config

### PR DESCRIPTION
**Pull request by bouland**
What do you thinks about this feature ?
Will add tests if yes.
```json
    "autoload": {
        "psr-4": {
            "MyNameSpace\\": "src",
            "MyNameSpace\\MyPlugin\\": "./plugins/MyPlugin/src"
        }
    },
```

Will generate `vendor/cakephp-plugins.php`

```php
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Duplicatable' => $baseDir . '/vendor/riesenia/cakephp-duplicatable/',
        'MyNameSpace/MyPlugin' => $baseDir . '/plugins/MyPlugin/',
        'Josegonzalez/Version' => $baseDir . '/vendor/josegonzalez/cakephp-version/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/'
    ]
];
```

### CODE REVIEW

**Comment by ADmad** [comment]
Why? What are you trying to achieve with this?

**Comment by bouland** [comment]
In short :
Namespace purpose is to deal with naming conflict, actual local plugin namespace is to strong, need to release this.
Long story :
When I write a new plugin I don't know if it will be shared afterword.
I start coding in local plugin/ but next if i published it under its own repo I need to rewrite all namespace and use statements for avoiding any colision with other community, could not publish with single generic word aka Duplicatable, Import, Export
Josegonzalez/Version is good exemple

**Comment by elboletaire** [comment]
@bouland why not properly set the namespaces from the beginning? I mean... I always use `\Cirici` as a prefix on my namespaces, wether it's an internal plugin, or an external one (installed using composer in vendor).

It's a bit more of work, but then the plugins work always in all conditions.

**Comment by ADmad** [comment]
As mentioned in above comment just prefix the namespace before hand to avoid future collisions.

**Pull request closed without merging**
