### PR TITLE
Don't use CakePHP code to generate config file.

### PR DESCRIPTION
**Pull request by markstory**
We can't rely on dependencies while installing dependencies. Instead use lower level PHP methods.

### CODE REVIEW

**Comment by ADmad** [comment]
Tests failing

**Comment by markstory** [comment]
I have no idea why HHVM is doing is eating glue.

**Comment by ADmad** [comment]
Hehe, should move the hhvm build to allowed failures

**Comment by ADmad** [comment]
Looks good to merge :+1:

**Pull request merged**
