### PR TITLE
Namespaced plugins should use "/"

### PR DESCRIPTION
**Pull request by dakota**
For example, "Ceeram\Blame" is not a valid CakePHP plugin, which prevents `Plugin::load()` from working correctly.

### CODE REVIEW

**Comment by ADmad** [comment]
Can you please add a test for this. Also there's a CS error.

**Comment by dakota** [comment]
I've added a test. The CS error is the same as https://github.com/cakephp/cakephp/pull/5715 and stems from https://github.com/squizlabs/PHP_CodeSniffer/issues/454

**Comment by dakota** [comment]
I can add a codeSniffIgnore around it like that PR did?

**Comment by ADmad** [comment]
I would suggest just changing the formatting instead of ignoring.

**Comment by dakota** [comment]
According to https://github.com/squizlabs/PHP_CodeSniffer/issues/454#issuecomment-71024710 the problem (as I understand it), isn't that the formatting is invalid (because it is valid imo according to PSR-2), but that CodeSniffer incorrectly reports it as invalid?

**Comment by ADmad** [comment]
Okay, feel free to do whatever you (and others) feel is right :)

**Comment by AD7six** [comment]
@dakota https://github.com/squizlabs/PHP_CodeSniffer/commit/ccf1f709f77fd8e0075d11c88b7f63816ccbb0ce - it was a deliberate change. We need something more conclusive than one of our own comments to know if our interpretation of the relevant text is accurate.

**Comment by dakota** [comment]
@AD7six Fair enough. I've fixed the error, will see what happens and change it back if needed.

**Pull request merged**
