### PR TITLE
Remove strict typing for PHP 5.6 compatibility

### PR DESCRIPTION
**Pull request by ADmad**
Refs #50.

### CODE REVIEW

**Review by dereuromark — APPROVED** [review]
I see, the PHP constraint would allow this.

**Comment by othercorey** [comment]
@nojimage Can you test this with 5.6 and composer 2?

**Comment by ravage84** [comment]
Wouldn't it make sense to re-add PHP 5.6-7.1 to Travis CI, then?

**Comment by ADmad** [comment]
Phpunit 8+ requires `: void` return typehint for `setUp()` method while lower versions don't. 

So running  the testsuite on all supported PHP versions  would either require modifying the test case file after installation or having separate files and running required one based on PHP one.

I personally am not interested in spending time on that.

**Comment by othercorey** [comment]
This is just a quick fix to have a version that's compatible so we can move on.

**Comment by nojimage** [comment]
It works fine on PHP 5.6 with composer 2.
thank you.

**Pull request merged**
